// Generates TypeScript protocol types from the C# DTOs:
//   OVSD.Host --export-schema <tmp>  ->  json-schema-to-typescript  ->  src/protocol/generated/*.ts
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from 'json-schema-to-typescript'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const hostProject = resolve(root, '../server/src/OVSD.Host')
const outDir = join(root, 'src/protocol/generated')
const schemaDir = mkdtempSync(join(tmpdir(), 'ovsd-schema-'))

try {
  execFileSync('dotnet', ['run', '--project', hostProject, '--', '--export-schema', schemaDir], { stdio: 'inherit' })
  mkdirSync(outDir, { recursive: true })
  for (const file of readdirSync(schemaDir).filter((f) => f.endsWith('.schema.json'))) {
    const schema = JSON.parse(readFileSync(join(schemaDir, file), 'utf8'))
    const ts = await compile(schema, schema.title, {
      bannerComment: '/* Generated by scripts/gen-types.mjs from the C# protocol. Do not edit. */',
      additionalProperties: false,
      style: { singleQuote: true, semi: false },
    })
    const target = join(outDir, file.replace('.schema.json', '.ts'))
    // Recursive step lists come out as "Items"; give them their real name.
    writeFileSync(target, ts.replace(/\bItems\b/g, 'Step'))
    console.log(`Wrote ${target}`)
  }
} finally {
  rmSync(schemaDir, { recursive: true, force: true })
}
