<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>OVSD.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OVSD.Core\OVSD.Core.csproj" />
    <ProjectReference Include="..\OVSD.Platform.Windows\OVSD.Platform.Windows.csproj" />
    <ProjectReference Include="..\OVSD.Integrations\OVSD.Integrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

</Project>
